runtime: python37

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

# env_variables:
#   MYSQL_DSN: mysql:unix_socket=/cloudsql/supple-folder-256709:asia-southeast1:dhl-project-2;dbname=guestbook
#   MYSQL_USER: root
#   MYSQL_PASSWORD: "0123199373"
